version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.1
workflows:
  e2e-tests:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          parallel: true
          parallelism: 3
          group: 3 machines
          post-steps:
            - slack/notify:
                context: Slack
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "*Notification for CircleCI builds*",
                            "emoji": true
                          }
                        ]
                      }
                    ]
                  }