version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  e2e-tests:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          parallel: true
          parallelism: 10
          group: 10 machines
          reports: mochawesome
      - store_test_results:
          path: mochawesome-report
